export const GOMOKU_BOARD_SIZE = 15
export const GOMOKU_VIEW_PADDING = 8
export const GOMOKU_BOARD_FRAME_INSET = 12
export const GOMOKU_BOARD_INNER_PADDING = 18
export const GOMOKU_MOBILE_POINTER_ALIGNMENT_OFFSET = 16
